module 7 tasks complete
js-tasks-ru/jsbasic-20241021_mfglad pull request #8
Opened 2024-11-28 11:18 UTC by maxfedorov

2024-11-28 11:19 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-28 20:11 UTC, SinimaWath requested changes

2024-11-28 20:11 UTC, SinimaWath commented on 7-module/1-task/index.js
> +  slides = null;
nit: это скорее приватное свойство: `#slides = []`

2024-11-28 20:11 UTC, SinimaWath commented on 7-module/1-task/index.js
> +      });
nit: Такой обработчик события, лучше унести в отдельный метод, чтобы код был более читаемым

2024-11-28 20:11 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.modal.querySelector('.modal__body').innerHTML = modalBody.outerHTML;
Тут так делать не стоит, таким методом, сбрасываются все обработчики события, нужно переделать на честный append:
```
this.modal.querySelector('.modal__body').innerHTML = ""
this.modal.querySelector('.modal__body').append(modalBody)
```

2024-11-28 20:11 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.modal.querySelector('.modal__close').addEventListener('click', () => this.close(), {once: true});
Обработчик события теперь одноразовый. И как только меню закроют один раз, второй раз у тебя уже не получится закрыть меню через крестик, так как обработчик события удалится

2024-11-28 21:54 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-11-28 22:00 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-29 15:33 UTC, SinimaWath approved these changes

2024-11-29 15:34 UTC, merged